Vagrant::Config.run do |config|
    # A freebsd image can be created with veewee
    # https://github.com/jedi4ever/veewee
    # 
    # vagrant basebox define freebsd freebsd-8.2-pcbsd-i386-netboot
    # vagrant basebox build freebsd
    # vagrant basebox export freebsd
    # vagrant box add freebsd freebsd.box
    config.vm.box = "freebsd"

    config.vm.guest = :freebsd
    
    # Note that virtualbox shared folders don't work with freebsd, so
    # we'd need nfs shared folders here even if virtualbox gains
    # support for symlinks.
    config.vm.network :hostonly, "172.19.1.3"
    # Name this v-root to clobber the default /vagrant mount point.
    # We can't mount it over nfs because there are apparently issues
    # when one nfs export is a subfolder of another.
    config.vm.share_folder("v-root", "/tornado", "../../..", :nfs => true)

    config.vm.provision :shell, :path => "setup.sh"
end