# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "chef/freebsd-10.0"

  config.vm.network "private_network", type: "dhcp"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder "../../..", "/tornado", type: "nfs"

  # Override the default /vagrant mapping to use nfs, since freebsd doesn't
  # support other folder types.
  config.vm.synced_folder ".", "/vagrant", type: "nfs"

  config.ssh.shell = "/bin/sh"

  config.vm.provision :shell, :path => "setup.sh"
end
