require 'vagrant/systems/freebsd'

Vagrant::Config.run do |config|
    # A freebsd image can be created with veewee
    # https://github.com/jedi4ever/veewee
    # 
    # vagrant basebox define freebsd freebsd-8.2-pcbsd-i386-netboot
    # vagrant basebox build freebsd
    # vagrant basebox export freebsd
    # vagrant box add freebsd freebsd.box
    config.vm.box = "freebsd"

    config.vm.system = :freebsd
    
    # Note that virtualbox shared folders don't work with freebsd, so
    # we'd need nfs shared folders here even if virtualbox gains
    # support for symlinks.
    config.vm.network "172.19.1.3"
    config.vm.share_folder("tornado", "/tornado", "../../..", :nfs => true)

    # This doesn't seem to get mounted by default for freebsd,
    # but that's actually a good thing since there are apparently issues
    # when one nfs export is a subfolder of another.
    #config.vm.share_folder("v-root", "/vagrant", ".", :nfs => true)

    config.vm.provision :shell, :path => "setup.sh"
end