#!/bin/bash
set -ex

# Get out of the source directory before running tests to avoid PYTHONPATH
# confusion.  This is necessary to ensure that the speedups module can
# be found in the installation directory.
cd maint

# Copy the coveragerc down so coverage.py can find it.
cp ../.coveragerc .

if [[ $TRAVIS_PYTHON_VERSION != 'pypy'* ]]; then
    export TORNADO_EXTENSION=1
fi

# Travis workers are often overloaded and cause our tests to exceed
# the default timeout of 5s.
export ASYNC_TEST_TIMEOUT=15

export TARGET="-m tornado.test.runtests"

# We use "python -m coverage" instead of the "bin/coverage" script
# so we can pass additional arguments to python.
# coverage needs a function that was removed in python 3.6 so we can't
# run it with nightly cpython.
if [[ $TRAVIS_PYTHON_VERSION != nightly ]]; then
    export TARGET="-m coverage run $TARGET"
fi

python $TARGET
python $TARGET --ioloop=tornado.platform.select.SelectIOLoop
python -O $TARGET
LANG=C python $TARGET
LANG=en_US.utf-8 python $TARGET
if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then
    python -bb $TARGET
fi
if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then
    python $TARGET --resolver=tornado.netutil.ThreadedResolver
fi
if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then
    python $TARGET --httpclient=tornado.curl_httpclient.CurlAsyncHTTPClient
fi
if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then
    python $TARGET --ioloop_time_monotonic
fi
if [[ $TRAVIS_PYTHON_VERSION != 'pypy'* ]]; then
    python $TARGET --ioloop=tornado.platform.twisted.TwistedIOLoop
fi
if [[ $TRAVIS_PYTHON_VERSION == 3.4 || $TRAVIS_PYTHON_VERSION == 3.5 ]]; then
    python $TARGET --ioloop=tornado.platform.asyncio.AsyncIOLoop
fi
if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then
    python $TARGET --ioloop=tornado.platform.asyncio.AsyncIOLoop
fi
if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then
    python $TARGET --resolver=tornado.platform.twisted.TwistedResolver
fi
# if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then
#     python $TARGET --resolver=tornado.platform.caresresolver.CaresResolver
# fi
if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then
    python $TARGET --ioloop_time_monotonic
fi
../nodeps/bin/python -m tornado.test.runtests

# make coverage reports for Codecov to find
if [[ $TRAVIS_PYTHON_VERSION != nightly ]]; then
    coverage xml
fi

export TORNADO_EXTENSION=0
if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then
    cd ../docs && mkdir sphinx-out && sphinx-build -E -n -W -b html . sphinx-out
fi
if [[ $TRAVIS_PYTHON_VERSION == '2.7' || $TRAVIS_PYTHON_VERSION == '3.5' ]]; then
    cd ../docs && mkdir sphinx-doctest-out && sphinx-build -E -n -b doctest . sphinx-out
fi
