#!/usr/bin/env python

from __future__ import print_function

import argparse
import os
from os.path import dirname, abspath
import subprocess
import sys

import six

import lister

exclude = """
tornado/test/gettext_translations/extract_me.py
demos/
maint/test/
docs/conf.py
setup.py
""".split()

parser = argparse.ArgumentParser(description="Run mypy on files tracked by git.")
parser.add_argument('targets', nargs='*', default=[],
                    help="""files and directories to include in the result.
                    If this is not specified, the current directory is used""")
parser.add_argument('-m', '--modified', action='store_true', default=False, help='list only modified files')
parser.add_argument('-a', '--all', dest='all', action='store_true', default=False,
                    help="""run mypy on all python files, ignoring the exclude list.
                    This is useful if you have to find out which files fail mypy check.""")
args = parser.parse_args()
if args.all:
    exclude = []

# find all non-excluded files in current directory
BASE_DIR = dirname(dirname(dirname(abspath(__file__))))
exclude = [os.path.join(BASE_DIR, fpath) for fpath in exclude]
python_files = lister.list_files(targets=args.targets, ftypes=['py'], use_shebang=False,
                                 modified_only=args.modified, exclude=exclude)

# TODO provide a handy way to install mypy, and use the result here if present
mypy_command = "mypy"

# run mypy
if python_files:
    try:
        # TODO --fast-parser
        # TODO --check-untyped-defs
        rc = subprocess.call([mypy_command, "--silent-imports", "--py2"] + python_files)
    except OSError:
        print("Failed to start mypy -- do you have it installed?")
        sys.exit(2)
    sys.exit(rc)
else:
    print("There are no files to run mypy on.")
