application: python-tornado-hrd
version: 3
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static/tornado-0.1.tar.gz
  script: website.application

- url: /static/tornado-0.2.tar.gz
  script: website.application

- url: /static/
  static_dir: static

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /documentation/?
  script: website.application

- url: /documentation
  static_dir: sphinx/build/html

- url: /.*
  script: website.application
