application: python-tornado
version: 1
runtime: python
api_version: 1

handlers:
- url: /static/tornado-0.1.tar.gz
  script: website.py

- url: /static/tornado-0.2.tar.gz
  script: website.py

- url: /static/
  static_dir: static

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /.*
  script: website.py
